# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Create the model cache directory
RUN mkdir -p /app/models

# Copy the downloaded model into the container
COPY ./models /app/models

# Set the environment variable to point to the local model cache
ENV HF_HOME=/app/models

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run app.py when the container launches
CMD ["python", "app.py"]